# Generated by Django 3.2.9 on 2021-11-19 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211116_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='paypal_button',
            field=models.TextField(default=''),
        ),
    ]
