# Generated by Django 3.2.9 on 2021-11-19 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_product_paypal_button'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='download_link',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.TextField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='product',
            name='paypal_button',
            field=models.TextField(blank=True, default=''),
        ),
    ]
