# Generated by Django 3.2.9 on 2021-11-19 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20211119_0306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='download_link',
            new_name='download_html',
        ),
    ]
