# Generated by Django 3.2.9 on 2021-11-19 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_download_link_product_download_html'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='download_html',
        ),
        migrations.AddField(
            model_name='product',
            name='file',
            field=models.FileField(blank=True, default='', upload_to='static/users/downloads/'),
        ),
    ]
